<%
require_relative 'libraries/helpers'
OktaOpenvpnBuild::Helpers.configure!(token: ENV['PACKAGECLOUD_TOKEN'])
%>

driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list: okta-openvpn-build::default
    attributes:
      okta_openvpn_build:
        version: <%= OktaOpenvpnBuild::Helpers.version %>
        revision: <%= OktaOpenvpnBuild::Helpers.revision %>
        packagecloud_token: <%= ENV['PACKAGECLOUD_TOKEN'] || 'test' %>
        publish_artifacts: <%= ENV['TRAVIS_PULL_REQUEST'] == 'false' ? true : false %>
