dist: xenial
language: ruby

branches:
  only:
    - master

sudo: required

install:
  - curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -c current -P chefdk -v 3
  - chef exec bundle install

script: chef exec microwave test

# The name "test" is special in Travis, so we have to call it that, even though
# it'd be more accurately named "integration_test_and_deploy".
stages:
  - name: unit
  - name: test
    if: NOT type = cron

jobs:
  include:
    - stage: unit
      script: chef exec rake
    - stage: test
