dist: xenial
language: ruby
rvm: system

branches:
  only:
    - master

sudo: required

install:
  - curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -c current -P chefdk
  - chef exec bundle install

env:
  - SUITE=default PLATFORM=ubuntu
  - SUITE=default PLATFORM=centos

script: chef exec microwave test $SUITE-$PLATFORM

# The name "test" is special in Travis, so we have to call it that, even though
# it'd be more accurately named "integration_test_and_deploy".
stages:
  - name: unit
  - name: test
    if: NOT type = cron AND branch = master

jobs:
  include:
    - stage: unit
      env:
      script: chef exec rake
